<a href="https://colab.research.google.com/github/jasmidd/MSSP6070/blob/main/WeeklyModules/Week06/Participation_Activity_Week6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'jasmidd'
repository = 'MSSP6070'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

import subprocess
subprocess.run(['git', 'clone', clone_url])

os.chdir(repository)
print(f"Changed directoGit_HUBry to: {os.getcwd()}")

Changed directoGit_HUBry to: /content/MSSP6070/MSSP6070

In [4]:
df = pd.read_csv('/content/MSSP6070/data/Student Performance Data.csv')

Original Data Frame

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

New Data Frames

In [6]:
group_a = lambda df: df[df['race/ethnicity'] == 'group A'].copy()
df_2 = group_a(df)
df_2.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
13,male,group A,some college,standard,78,72,70,220,completed,medium
14,female,group A,master's degree,standard,50,53,58,161,none,medium
25,male,group A,master's degree,free/reduced,73,74,72,219,none,medium
46,female,group A,associate's degree,standard,55,65,62,182,completed,medium

In [7]:
high_parental_edu = lambda df: df[df['parental level of education'] == 'master\'s degree'].copy()
df_3 = high_parental_edu(df)
df_3.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
2,female,group B,master's degree,standard,90,95,93,278,none,high
14,female,group A,master's degree,standard,50,53,58,161,none,medium
18,male,group C,master's degree,free/reduced,46,42,46,134,completed,low
25,male,group A,master's degree,free/reduced,73,74,72,219,none,medium
29,female,group D,master's degree,standard,62,70,75,207,none,medium