<a href="https://colab.research.google.com/github/jasmidd/MSSP6070/blob/main/Assignments/Participation_Activity__Week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.

In [ ]:
!git clone https://github.com/jasmidd/MSSP6070.git

fatal: destination path 'MSSP6070' already exists and is not an empty directory.

In [ ]:
import pandas as pd

2. b)

In [ ]:
apple = pd.read_csv('/content/MSSP6070/data/aapl.csv')
amazon = pd.read_csv('/content/MSSP6070/data/amzn.csv')
netflix = pd.read_csv('/content/MSSP6070/data/nflx.csv')
facebook = pd.read_csv('/content/MSSP6070/data/fb.csv')
google = pd.read_csv('/content/MSSP6070/data/goog.csv')

In [ ]:
apple.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

2. c)

In [ ]:
apple['ticker'] = 'AAPL'
amazon['ticker'] = 'AMZN'
netflix['ticker'] = 'NFLX'
facebook['ticker'] = 'FB'
google['ticker'] = 'GOOG'

In [ ]:
apple.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

2. d)

In [ ]:
faang = pd.concat(
    [apple, amazon, netflix, facebook, google],
    ignore_index=True
)

In [ ]:
faang.shape

(1255, 7)

2. e)

In [ ]:
faang.to_csv('/content/MSSP6070/data/faang.csv', index=False)

2. f)

In [ ]:
faang = pd.read_csv('/content/MSSP6070/data/faang.csv')

In [ ]:
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype('int')
faang.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

In [ ]:
faang = faang.sort_values(
    by=['date', 'ticker']
)
faang.head()

           date       open       high        low      close    volume ticker
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
251  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
753  2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
502  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

2. g)

In [ ]:
top_7_volume = faang.nlargest(7, 'volume')
top_7_volume

          date      open      high       low     close     volume ticker
895 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
806 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
810 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
807 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

2. h)

In [ ]:
melted = pd.melt(faang, ['date', 'ticker'])
faang_melted = melted.sort_values(
    by=['date', 'ticker']
)
faang_melted.head()

           date ticker variable         value
0    2018-01-02   AAPL     open  1.669271e+02
1255 2018-01-02   AAPL     high  1.690264e+02
2510 2018-01-02   AAPL      low  1.660442e+02
3765 2018-01-02   AAPL    close  1.689872e+02
5020 2018-01-02   AAPL   volume  2.555593e+07